"""Add Product and ProductReview models

Revision ID: 3d3ce651a479
Revises: 9067b640ca3d
Create Date: 2026-10-05 17:06:24.433012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3ce651a479'
down_revision: Union[str, Sequence[str], None] = '9067b640ca3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_campaigns_product_id'), 'campaigns', ['product_id'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_product_id'), table_name='campaigns')
    op.drop_column('campaigns', 'product_id')
    # ### end Alembic commands ###
