"""initial schema

Revision ID: 47f7bf985e55
Revises: 
Create Date: 2026-09-30 11:06:47.689696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f7bf985e55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('sales', sa.Float(), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_daily_date'), 'metrics_daily', ['date'], unique=False)
    op.create_index(op.f('ix_metrics_daily_entity_id'), 'metrics_daily', ['entity_id'], unique=False)
    op.create_index(op.f('ix_metrics_daily_id'), 'metrics_daily', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ads_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_accounts_id'), 'ads_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_ads_accounts_profile_id'), 'ads_accounts', ['profile_id'], unique=True)
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_messages_id'), 'ai_chat_messages', ['id'], unique=False)
    op.create_table('ai_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ads_account_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ads_account_id'], ['ads_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_suggestions_id'), 'ai_suggestions', ['id'], unique=False)
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ads_account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ads_account_id'], ['ads_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_rules_id'), 'automation_rules', ['id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ads_account_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('daily_budget', sa.Float(), nullable=True),
    sa.Column('targeting_type', sa.String(), nullable=True),
    sa.Column('campaign_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ads_account_id'], ['ads_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_external_id'), 'campaigns', ['external_id'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('ad_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('default_bid', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_groups_external_id'), 'ad_groups', ['external_id'], unique=False)
    op.create_index(op.f('ix_ad_groups_id'), 'ad_groups', ['id'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_group_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('keyword_text', sa.String(), nullable=False),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_external_id'), 'keywords', ['external_id'], unique=False)
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.create_table('search_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('search_term', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('ad_group_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('sales', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_terms_date'), 'search_terms', ['date'], unique=False)
    op.create_index(op.f('ix_search_terms_id'), 'search_terms', ['id'], unique=False)
    op.create_index(op.f('ix_search_terms_search_term'), 'search_terms', ['search_term'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_terms_search_term'), table_name='search_terms')
    op.drop_index(op.f('ix_search_terms_id'), table_name='search_terms')
    op.drop_index(op.f('ix_search_terms_date'), table_name='search_terms')
    op.drop_table('search_terms')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_external_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_ad_groups_id'), table_name='ad_groups')
    op.drop_index(op.f('ix_ad_groups_external_id'), table_name='ad_groups')
    op.drop_table('ad_groups')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_external_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_automation_rules_id'), table_name='automation_rules')
    op.drop_table('automation_rules')
    op.drop_index(op.f('ix_ai_suggestions_id'), table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    op.drop_index(op.f('ix_ai_chat_messages_id'), table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    op.drop_index(op.f('ix_ads_accounts_profile_id'), table_name='ads_accounts')
    op.drop_index(op.f('ix_ads_accounts_id'), table_name='ads_accounts')
    op.drop_table('ads_accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_metrics_daily_id'), table_name='metrics_daily')
    op.drop_index(op.f('ix_metrics_daily_entity_id'), table_name='metrics_daily')
    op.drop_index(op.f('ix_metrics_daily_date'), table_name='metrics_daily')
    op.drop_table('metrics_daily')
    # ### end Alembic commands ###
