"""sync neon with local schema updates auth and ads mock

Revision ID: 9067b640ca3d
Revises: 9cf02f93f6ea
Create Date: 2026-10-03 13:16:15.763208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9067b640ca3d'
down_revision: Union[str, Sequence[str], None] = '9cf02f93f6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'ad_groups',
        existing_comment='Ad groups within a campaign',
        schema=None
    )
    op.add_column('ads_accounts', sa.Column('is_mock', sa.Boolean(), nullable=True))
    op.add_column('ads_accounts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('ads_accounts', 'profile_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='The external ID from Amazon Ads provider',
               existing_nullable=True)
    op.drop_table_comment(
        'ads_accounts',
        existing_comment='One row per connected Amazon Ads account, linked to a user',
        schema=None
    )
    op.drop_table_comment(
        'ai_chat_messages',
        existing_comment='History of AI chat interactions for the user',
        schema=None
    )
    op.drop_table_comment(
        'ai_suggestions',
        existing_comment='AI-generated optimization suggestions',
        schema=None
    )
    op.drop_table_comment(
        'automation_rules',
        existing_comment='User-defined rules for bid and budget automation',
        schema=None
    )
    op.drop_table_comment(
        'campaigns',
        existing_comment='Advertising campaigns synchronized from provider',
        schema=None
    )
    op.drop_table_comment(
        'keywords',
        existing_comment='Keywords targeted by ad groups',
        schema=None
    )
    op.add_column('metrics_daily', sa.Column('organic_sales', sa.Float(), nullable=True))
    op.drop_table_comment(
        'metrics_daily',
        existing_comment='Daily performance metrics for campaigns/ad groups',
        schema=None
    )
    op.drop_table_comment(
        'search_terms',
        existing_comment='Actual search terms that triggered ads',
        schema=None
    )
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_table_comment(
        'users',
        existing_comment='User accounts and authentication data',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'User accounts and authentication data',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'google_id')
    op.create_table_comment(
        'search_terms',
        'Actual search terms that triggered ads',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'metrics_daily',
        'Daily performance metrics for campaigns/ad groups',
        existing_comment=None,
        schema=None
    )
    op.drop_column('metrics_daily', 'organic_sales')
    op.create_table_comment(
        'keywords',
        'Keywords targeted by ad groups',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'campaigns',
        'Advertising campaigns synchronized from provider',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'automation_rules',
        'User-defined rules for bid and budget automation',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'ai_suggestions',
        'AI-generated optimization suggestions',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'ai_chat_messages',
        'History of AI chat interactions for the user',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'ads_accounts',
        'One row per connected Amazon Ads account, linked to a user',
        existing_comment=None,
        schema=None
    )
    op.alter_column('ads_accounts', 'profile_id',
               existing_type=sa.VARCHAR(),
               comment='The external ID from Amazon Ads provider',
               existing_nullable=True)
    op.drop_column('ads_accounts', 'created_at')
    op.drop_column('ads_accounts', 'is_mock')
    op.create_table_comment(
        'ad_groups',
        'Ad groups within a campaign',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###
