"""Add campaign models V2

Revision ID: db4a2108e7f8
Revises: 3d3ce651a479
Create Date: 2026-10-09 07:19:31.266427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4a2108e7f8'
down_revision: Union[str, Sequence[str], None] = '3d3ce651a479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_campaign_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('acos_low', sa.Float(), nullable=False),
    sa.Column('acos_high', sa.Float(), nullable=False),
    sa.Column('default_target_acos', sa.Float(), nullable=False),
    sa.Column('bid_limit_acos', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_campaign_settings_id'), 'user_campaign_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_campaign_settings_user_id'), 'user_campaign_settings', ['user_id'], unique=True)
    op.create_table('campaign_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'product_id', name='uix_campaign_product')
    )
    op.create_index(op.f('ix_campaign_products_campaign_id'), 'campaign_products', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_products_id'), 'campaign_products', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_products_product_id'), 'campaign_products', ['product_id'], unique=False)
    op.create_table('negative_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('ad_group_id', sa.Integer(), nullable=True),
    sa.Column('keyword_text', sa.String(), nullable=False),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.CheckConstraint("match_type IN ('NEGATIVE_EXACT', 'NEGATIVE_PHRASE')", name='ck_negative_keyword_match_type'),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'ad_group_id', 'keyword_text', 'match_type', name='uix_negative_keyword')
    )
    op.create_index(op.f('ix_negative_keywords_ad_group_id'), 'negative_keywords', ['ad_group_id'], unique=False)
    op.create_index(op.f('ix_negative_keywords_campaign_id'), 'negative_keywords', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_negative_keywords_id'), 'negative_keywords', ['id'], unique=False)
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_group_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.CheckConstraint("NOT (kind = 'AUTO_GROUP' AND value NOT IN ('CLOSE_MATCH', 'LOOSE_MATCH', 'SUBSTITUTES', 'COMPLEMENTS'))", name='ck_target_auto_value'),
    sa.CheckConstraint("kind IN ('AUTO_GROUP', 'ASIN', 'CATEGORY', 'NEGATIVE_ASIN')", name='ck_target_kind'),
    sa.CheckConstraint("state IN ('ENABLED', 'PAUSED', 'ARCHIVED')", name='ck_target_state'),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_ad_group_id'), 'targets', ['ad_group_id'], unique=False)
    op.create_index(op.f('ix_targets_id'), 'targets', ['id'], unique=False)
    op.add_column('campaigns', sa.Column('start_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    op.add_column('campaigns', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('campaigns', sa.Column('bidding_strategy', sa.String(), server_default='AUTO_FOR_SALES', nullable=False))
    op.add_column('campaigns', sa.Column('placement_top_pct', sa.Integer(), server_default='0', nullable=False))
    op.add_column('campaigns', sa.Column('placement_rest_pct', sa.Integer(), server_default='0', nullable=False))
    op.add_column('campaigns', sa.Column('placement_product_page_pct', sa.Integer(), server_default='0', nullable=False))
    op.add_column('campaigns', sa.Column('target_acos', sa.Float(), nullable=True))
    op.add_column('campaigns', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('campaigns', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_campaigns_ads_account_id'), table_name='campaigns')
    op.create_index('ix_campaigns_account_state', 'campaigns', ['ads_account_id', 'state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_campaigns_account_state', table_name='campaigns')
    op.create_index(op.f('ix_campaigns_ads_account_id'), 'campaigns', ['ads_account_id'], unique=False)
    op.drop_column('campaigns', 'updated_at')
    op.drop_column('campaigns', 'created_at')
    op.drop_column('campaigns', 'target_acos')
    op.drop_column('campaigns', 'placement_product_page_pct')
    op.drop_column('campaigns', 'placement_rest_pct')
    op.drop_column('campaigns', 'placement_top_pct')
    op.drop_column('campaigns', 'bidding_strategy')
    op.drop_column('campaigns', 'end_date')
    op.drop_column('campaigns', 'start_date')
    op.drop_index(op.f('ix_targets_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_ad_group_id'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_negative_keywords_id'), table_name='negative_keywords')
    op.drop_index(op.f('ix_negative_keywords_campaign_id'), table_name='negative_keywords')
    op.drop_index(op.f('ix_negative_keywords_ad_group_id'), table_name='negative_keywords')
    op.drop_table('negative_keywords')
    op.drop_index(op.f('ix_campaign_products_product_id'), table_name='campaign_products')
    op.drop_index(op.f('ix_campaign_products_id'), table_name='campaign_products')
    op.drop_index(op.f('ix_campaign_products_campaign_id'), table_name='campaign_products')
    op.drop_table('campaign_products')
    op.drop_index(op.f('ix_user_campaign_settings_user_id'), table_name='user_campaign_settings')
    op.drop_index(op.f('ix_user_campaign_settings_id'), table_name='user_campaign_settings')
    op.drop_table('user_campaign_settings')
    # ### end Alembic commands ###
